# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy Github Pages

on:
  push:
    branches: [main]

jobs:
  update-github-pages:
    name: deploy github pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Build
        run: npm run experience
      - name: Deploy github pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
