# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Npm Package

on:
  push:
    branches:
      - "main"
    paths:
      - "package.json"

jobs:
  publish-npm:
    name: publish npm package
    runs-on: ubuntu-latest
    steps:
      - name: Check File
        run: |
          if git diff --unified=0 ${{ github.event.before }} ${{ github.sha }} 'package.json' | grep -E "^\+.*version:"; then
            echo "Version Changed"
          else
            echo "Version Unchanged"
          fi
      - name: Checkout
        if: success()
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
