# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Npm Package

on:
  push:
    branches:
      - "main"
    paths:
      - "package.json"

jobs:
  publish-npm:
    name: publish npm package
    runs-on: ubuntu-latest
    steps:
      - name: Check File
        run: |
          if git diff --unified=0 ${{ github.event.before }} ${{ github.sha }} 'package.json' | grep -E "^\+.*version:"; then
            echo "Version Changed"
          else
            echo "Version Unchanged"
          fi
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
